### ISSUE TITLE
Toward new release

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/libpyvinyl#43]
- #37 Jun will fix the CI errors and be ready to be merged next week.
- #36 Shervin needs someone to review it.
    - Jun will review it
- #38 is not critical. It will happen after the new release

The merging order (in a rebase way) would be:
- [x] PR #39: removing numpy depencency and the specialized calculator
- [x] PR #40: splitting the  requirements list in `dev` and `prod`
- [x] PR #36: pint library
- [x] PR #37: data class
- [x] PR #47: BaseCalculator
- [x] Documentation tests
- [x] run black on the entire code to have a coherent formatting
- [ ] add some commented header in each file with an agreed content (if needed)

#39, #40, #36 will be reviewed this week (CW 3) and merged next week (CW4)
#37 will be reviewed next week (CW4) and expected to be merged no later than the end of CW5. is merged in CW6.
#47 is expected to be reviewed in CW6 and merged in CW7.
Documentation tests are expected to finish in CW7.

Automatic documentation (docstrings) will be updated in the release, the non-automatic part will be written after the release. The documents should be included in the deliverable in May.

After cleaning up the PRs, a new version will be released on pip before Feb. 4th. The version number would be `0.1.0`.

**Comment by shervin86** [comment]
@JunCEEE can we start merging #39 ?

**Comment by JunCEEE** [comment]
@shervin86 Yes, I think we can, or do you think it needs more reviews?

**Comment by shervin86** [comment]
I'm going to merge it.

**Comment by shervin86** [comment]
Further tasks before making a release:
 - [ ] run `black` on the entire code to have a coherent formatting
 - [ ] add some commented header in each file with an agreed content (if needed)

**Comment by shervin86** [comment]
New release done.
